name: Build PyInstaller EXE

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build EXE
    runs-on: windows-latest  # change to ubuntu-latest for Linux build

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pyqt6 pandas requests

      # 4️⃣ Build with PyInstaller
      - name: Build EXE
        run: |
          pyinstaller --onefile --add-data "config.ini;." crypto_tracker.py

      # 5️⃣ Upload artifact
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: crypto_tracker
          path: dist/crypto_tracker.exe
